### ISSUE TITLE
201608082256 Error: Unexpected token }

### ISSUE THREAD

**Issue by netarchitech** [netarchitech/language-thinkscript#2]
grammars\thinkscript.cson12:20
CRLFUTF-8CoffeeScript
Failed to load the language-thinkscript package
Unexpected token } in C:\Users\Matt.atom\packages\language-thinkscript\package.json
Hide Stack Trace
SyntaxError: Unexpected token }
    at Object.parse (native)
    at parseObject (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.module.exports.readFileSync (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\season\lib\cson.js:170:14)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:700:29)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:423:36)
    at C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Matt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\atom-environment.js:749:28
  at C:\Users\Matt.atom\packages\language-thinkscript\package.json:1:1

Can't figure this one out...

**Comment by netarchitech** [comment]
Rewrote thinkscript.cson - no error present - close issue...
